---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: appflowy-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: appflowy
      owner: appflowy
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
  postgresql:
    extensions:
      - name: vector
        image:
          reference: ghcr.io/cloudnative-pg/postgresql-extension-pgvector:18
