---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appflowy-db-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: appflowy-db-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/appflowy
        property: db_password
