---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appflowy-db-app
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: appflowy-db-app
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: secret/appflowy
        property: database_url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appflowy-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: appflowy-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: secret/appflowy
        property: jwt_secret
