---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appflowy-db-app
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: appflowy-db-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        uri: "postgres://appflowy:{{ .db_password }}@127.0.0.1:5432/appflowy"
  data:
    - secretKey: db_password
      remoteRef:
        key: secret/appflowy
        property: db_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appflowy-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: appflowy-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: secret/appflowy
        property: jwt_secret
