---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: librechat
  namespace: default
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/danny-avila/librechat-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librechat
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: librechat
      sourceRef:
        kind: HelmRepository
        name: librechat
        namespace: default
      interval: 24h
  values:
    librechat:
      existingConfigYaml: librechat-config
      imageVolume:
        enabled: false
    volumes:
      - name: images-volume
        persistentVolumeClaim:
          claimName: data-pvc
    volumeMounts:
      - name: images-volume
        mountPath: /app/client/public/images
        subPath: librechat/images
    podSecurityContext:
      fsGroup: 2000
      fsGroupChangePolicy: OnRootMismatch
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
    mongodb:
      enabled: true
      image:
        repository: mongo
        tag: "latest"
      auth:
        enabled: false
      persistence:
        enabled: true
        existingClaim: data-pvc
        subPath: librechat/mongodb
      podSecurityContext:
        fsGroup: 999
        fsGroupChangePolicy: "OnRootMismatch"
      containerSecurityContext:
        runAsUser: 999
        runAsGroup: 999
    meilisearch:
      enabled: true
      persistence:
        enabled: true
        existingClaim: data-pvc
      extraVolumeMounts:
        - name: data
          mountPath: /meili_data
          subPath: librechat/meilisearch
      auth:
        existingMasterKeySecret: "librechat-credentials-env"
    controllers:
      main:
        containers:
          main:
            envFrom:
              - secretRef:
                  name: librechat-credentials-env
    service:
      type: ClusterIP
      port: 3080
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-issuer
        traefik.ingress.k8s.io/router.entrypoints: websecure
      hosts:
        - host: librechat.veirt.web.id
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: librechat-tls
          hosts:
            - librechat.veirt.web.id
