---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: librechat
  namespace: default
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/danny-avila/librechat-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librechat
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: librechat
      sourceRef:
        kind: HelmRepository
        name: librechat
        namespace: default
      interval: 24h
  values:
    librechat:
      imageVolume:
        enabled: false
    volumes:
      - name: images-volume
        persistentVolumeClaim:
          claimName: storage2-pvc
    volumeMounts:
      - name: images-volume
        mountPath: /app/client/public/images
        subPath: librechat/images
    mongodb:
      enabled: true
      auth:
        enabled: false
      persistence:
        enabled: true
        existingClaim: storage2-pvc
        subPath: librechat/mongodb
    meilisearch:
      enabled: true
      persistence:
        enabled: true
        existingClaim: storage2-pvc
        subPath: librechat/meilisearch
      auth:
        existingMasterKeySecret: "librechat-credentials-env"
    controllers:
      main:
        containers:
          main:
            envFrom:
              - secretRef:
                  name: librechat-credentials-env
    service:
      main:
        ports:
          http:
            port: 3080
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: cloudflare-issuer
          traefik.ingress.k8s.io/router.entrypoints: websecure
        hosts:
          - host: librechat.veirt.web.id
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - librechat.veirt.web.id
            secretName: librechat-tls
