---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-secrets
  namespace: default
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: librechat-credentials-env
    creationPolicy: Owner
  data:
    - secretKey: CLAUDE_API_KEY
      remoteRef:
        key: secret/librechat
        property: claude_api_key
    - secretKey: CREDS_IV
      remoteRef:
        key: secret/librechat
        property: creds_iv
    - secretKey: CREDS_KEY
      remoteRef:
        key: secret/librechat
        property: creds_key
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: secret/librechat
        property: gemini_api_key
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: secret/librechat
        property: jwt_refresh_secret
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/librechat
        property: jwt_secret
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: secret/librechat
        property: meili_master_key
