---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-service
spec:
  selector:
    app: adguard-home
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: webui
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns-tcp
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns-udp
  type: LoadBalancer
