---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      securityContext:
        runAsUser: 5984
        runAsGroup: 5984
        fsGroup: 5984
      containers:
        - name: couchdb
          image: couchdb:latest
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-secrets
                  key: COUCHDB_USER
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-secrets
                  key: COUCHDB_PASSWORD
          ports:
            - containerPort: 5984
          volumeMounts:
            - name: couchdb-volume
              mountPath: /opt/couchdb/data
              subPath: couchdb/data
            - name: couchdb-volume
              mountPath: /opt/couchdb/etc/local.d
              subPath: couchdb/config
      volumes:
        - name: couchdb-volume
          persistentVolumeClaim:
            claimName: data-pvc
