---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karakeep
resources:
  - namespace.yaml
  - web-deployment.yaml
  - web-service.yaml
  - chrome-deployment.yaml
  - chrome-service.yaml
  - meilisearch-deployment.yaml
  - meilisearch-service.yaml
  - secret.yaml
  - storage.yaml
  - ingress.yaml
