---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: karakeep-secrets
    creationPolicy: Owner
  data:
    - secretKey: meili_master_key
      remoteRef:
        key: secret/karakeep
        property: meili_master_key
    - secretKey: nextauth_secret
      remoteRef:
        key: secret/karakeep
        property: nextauth_secret
    - secretKey: next_public_secret
      remoteRef:
        key: secret/karakeep
        property: next_public_secret
