---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: karakeep-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/nfs
    server: rhea
  mountOptions:
    - vers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: karakeep-pv
  storageClassName: ""
