---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep-web
  template:
    metadata:
      labels:
        app: karakeep-web
      annotations:
        io.containerd.runc.v2.group: "zeropod"
        zeropod.ctrox.dev/container-names: "web"
        zeropod.ctrox.dev/ports-map: "web=3000"
        zeropod.ctrox.dev/scaledown-duration: 10s
    spec:
      runtimeClassName: zeropod
      containers:
        - name: web
          image: ghcr.io/karakeep-app/karakeep:0.24.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: KARAKEEP_VERSION
              value: release
            - name: MEILI_ADDR
              value: http://meilisearch:7700
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: meili_master_key
            - name: BROWSER_WEB_URL
              value: http://chrome:9222
            - name: DATA_DIR
              value: /data
            - name: NEXTAUTH_URL
              value: http://localhost:3000
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: nextauth_secret
            - name: NEXT_PUBLIC_SECRET
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: next_public_secret
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: karakeep/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: karakeep-pvc
