---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: ghcr.io/searxng/searxng:2025.7.26-1baf3dc
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/searxng
              subPath: searxng
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: data-pvc
