---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/sata-ssd
    server: rhea
  mountOptions:
    - vers=4.2
    - noatime
    - nodiratime
    - hard
    - tcp
