---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/storage
    server: hera
  mountOptions:
    - vers=4.2
    - noatime
    - nodiratime
    - hard
    - tcp
