---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/nfs
    server: rhea
  mountOptions:
    - vers=4.2
    - noatime
    - nodiratime
    - hard
    - tcp
