---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openclaw-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: openclaw
    name: openclaw
  mountOptions:
    - vers=4.2
    - noatime
    - nodiratime
    - hard
    - tcp
  nfs:
    server: rhea
    path: /root/nfs/openclaw
