---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage2-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
  volumeName: storage2-pv
  storageClassName: ""
