---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage3-pv
spec:
  capacity:
    storage: 298Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/storage3
    server: rhea
  mountOptions:
    - vers=4.2
    - noatime
    - nodiratime
    - hard
    - tcp
