---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage3-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 298Gi
  volumeName: storage3-pv
  storageClassName: ""
