---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-secrets
  namespace: default
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gitlab-secrets
    creationPolicy: Owner
  data:
    - secretKey: initial_root_password
      remoteRef:
        key: secret/gitlab
        property: initial_root_password
