---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kaneo-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: kaneo-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt_access
      remoteRef:
        key: secret/kaneo
        property: jwt_access
