---
apiVersion: v1
kind: Service
metadata:
  name: schedula-service
spec:
  selector:
    app: schedula
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: LoadBalancer
