---
apiVersion: v1
kind: Namespace
metadata:
  name: portainer
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 24h
  url: https://portainer.github.io/k8s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 6h
  releaseName: portainer
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: portainer
      interval: 24h
  values:
    service:
      type: LoadBalancer
    tls:
      force: true
    image:
      tag: lts
