apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appflowy-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: appflowy-db-pv
  storageClassName: ""
