apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: appflowy-db
spec:
  selector:
    matchLabels:
      app: appflowy-db
  serviceName: appflowy-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: appflowy-db
    spec:
      containers:
        - name: postgres
          image: ankane/pgvector:latest
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: appflowy
            - name: POSTGRES_USER
              value: appflowy
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appflowy-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: appflowy-db
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: appflowy-db-pvc
