---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.11.1
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: hoarder-secrets
                  key: meili_master_key
          volumeMounts:
            - name: meilisearch
              mountPath: /meili_data
              subPath: hoarder/meilisearch
      volumes:
        - name: meilisearch
          persistentVolumeClaim:
            claimName: nfs-pvc
