---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hoarder-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: hoarder-secrets
    creationPolicy: Owner
  data:
    - secretKey: meili_master_key
      remoteRef:
        key: secret/hoarder
        property: meili_master_key
    - secretKey: nextauth_secret
      remoteRef:
        key: secret/hoarder
        property: nextauth_secret
    - secretKey: next_public_secret
      remoteRef:
        key: secret/hoarder
        property: next_public_secret
