---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoarder-web
  template:
    metadata:
      labels:
        app: hoarder-web
    spec:
      containers:
        - name: web
          image: ghcr.io/hoarder-app/hoarder:0.22.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: HOARDER_VERSION
              value: release
            - name: MEILI_ADDR
              value: http://meilisearch:7700
            - name: BROWSER_WEB_URL
              value: http://chrome:9222
            - name: DATA_DIR
              value: /data
            - name: NEXTAUTH_URL
              value: http://localhost:3000
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: hoarder-secrets
                  key: nextauth_secret
            - name: NEXT_PUBLIC_SECRET
              valueFrom:
                secretKeyRef:
                  name: hoarder-secrets
                  key: next_public_secret
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: hoarder/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-pvc
