---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wakapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wakapi
  template:
    metadata:
      labels:
        app: wakapi
      annotations:
        io.containerd.runc.v2.group: "zeropod"
        zeropod.ctrox.dev/container-names: "wakapi"
        zeropod.ctrox.dev/ports-map: "wakapi=3000"
        zeropod.ctrox.dev/scaledown-duration: 10s
    spec:
      runtimeClassName: zeropod
      containers:
        - name: wakapi
          image: ghcr.io/muety/wakapi:2.13.3
          env:
            - name: WAKAPI_PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: wakapi-secrets
                  key: password_salt
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data-volume
              mountPath: /data
              subPath: wakapi
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
