---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wakapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wakapi
  template:
    metadata:
      labels:
        app: wakapi
    spec:
      containers:
        - name: wakapi
          image: ghcr.io/muety/wakapi:2.13.3
          env:
            - name: WAKAPI_PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: wakapi-secrets
                  key: password_salt
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data-volume
              mountPath: /data
              subPath: wakapi
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
