---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wakapi-secrets
  namespace: default
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: wakapi-secrets
    creationPolicy: Owner
  data:
    - secretKey: password_salt
      remoteRef:
        key: secret/wakapi
        property: password_salt
