---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: private
  namespace: flux-system
spec:
  interval: 1h
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: https://github.com/Veirt/homelab-gitops-private.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30m
  path: ./apps
  prune: true
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-private
  namespace: flux-system
spec:
  interval: 30m
  path: ./apps
  prune: true
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: private
  wait: true
