---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-openclaw
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/nfs
    server: rhea
  mountOptions:
    - vers=4.2
    - noatime
    - nodiratime
    - hard
    - tcp
