---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: convertx-secrets
  namespace: default
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: convertx-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: secret/convertx
        property: jwt_secret
