---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cypht-secret
  namespace: default
spec:
  refreshInterval: 168h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cypht-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: secret/cypht
        property: admin_password
    - secretKey: gmail-client-id
      remoteRef:
        key: secret/cypht
        property: gmail_client_id
    - secretKey: gmail-client-secret
      remoteRef:
        key: secret/cypht
        property: gmail_client_secret
