---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-app
  namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
  username: grafana
  password: Vq1ayv2tQs2ZGQ2PPA3v7khChy5hWjTfLrO1JV8mnl5jSvrJQUacrNDIdlOQzKqQ
