---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-ngx
  template:
    metadata:
      labels:
        app: paperless-ngx
      annotations:
        io.containerd.runc.v2.group: "zeropod"
        zeropod.ctrox.dev/scaledown-duration: 10s
    spec:
      runtimeClassName: zeropod
      containers:
        - name: broker
          image: docker.io/library/redis:7
          volumeMounts:
            - name: data-volume
              mountPath: /data
              subPath: paperless-ngx/redis
        - name: paperless-ngx
          image: ghcr.io/paperless-ngx/paperless-ngx:2.15.2
          env:
            - name: PAPERLESS_TIME_ZONE
              value: "Asia/Makassar"
            - name: PAPERLESS_REDIS
              value: "redis://localhost:6379"
            - name: PAPERLESS_OCR_LANGUAGE
              value: "ind"
            - name: PAPERLESS_OCR_LANGUAGES
              value: "ind"
            - name: PAPERLESS_URL
              value: "https://paperless.veirt.web.id"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data-volume
              mountPath: /usr/src/paperless/data
              subPath: paperless-ngx/data
            - name: data-volume
              mountPath: /usr/src/paperless/media
              subPath: paperless-ngx/media
            - name: data-volume
              mountPath: /usr/src/paperless/export
              subPath: paperless-ngx/export
            - name: data-volume
              mountPath: /usr/src/paperless/consume
              subPath: paperless-ngx/consume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
